name = "cf-workers"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-21"

[build]
command = "chmod +x build.sh && ./build.sh"

[durable_objects]
bindings = [
  { name = "CANISTER_DATA", class_name = "CanisterData" }
]

[triggers]
crons = ["*/10 * * * *"]

[[migrations]]
tag = "v1"
new_classes = ["CanisterData"]

[env.production.vars]
API_HOST = ""